name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deb:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Install tools
        run: brew install make dpkg ldid

      - name: Build
        run: env -u MAKELEVEL gmake -C tweak clean package

      - name: Upload Artifacts (.deb & .dylib)
        uses: actions/upload-artifact@v4
        with:
          name: spotifyglass-build
          path: |
            tweak/packages/*.deb
            tweak/.theos/obj/arm64/*.dylib
            tweak/.theos/obj/debug/*.dylib
            tweak/.theos/obj/*.dylib
